### ISSUE TITLE
[1.19.1] Mixin apply failed.

### ISSUE THREAD

**Issue by VoiidInVaiin** [DakotaPride/vanilla-claws-forge#1]
Problem: Mixin apply failed, Game fails to load and returns to launcher.
Version: 1.19.1
Mod Version: vanilla_claws-1.0.1.jar

Full log: https://pastebin.com/r5B14J5s

**Comment by DakotaPride** [comment]
I apologize for this issue, but I am currently working to resolve it! Hopefully, it can be fixed soon, as I'm sure many other people are experiencing this.

**Comment by DakotaPride** [comment]
Should now be fixed in both [1.19.1](https://www.curseforge.com/minecraft/mc-mods/banilla-claws-forge/files/3914551) and [1.18.2](https://www.curseforge.com/minecraft/mc-mods/banilla-claws-forge/files/3914552)
